HACKING.md
LICENSE
README.md
package.json
scripts/fetch-api-spec
src/components/links/BaseLink/BaseLink.test.tsx
src/components/links/BaseLink/BaseLink.tsx
vite.config.ts

- cherry-picked the packaging/license changes from main.

Upstream package/license changes

---

src/components/FormikSubmitButton/FormikSubmitButton.test.tsx
src/components/FormikSubmitButton/FormikSubmitButton.tsx
src/components/FormikSubmitButton/types.ts
src/components/PanelForm/PanelForm.tsx
src/components/PanelForm/types.ts
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
src/components/pages/Groups/AddGroupPanel/index.ts
src/components/pages/Groups/AddGroupPanel/types.ts
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/GroupPanel/index.ts
src/components/pages/Groups/GroupPanel/types.ts
src/components/pages/Groups/Groups.tsx

- Add a panel for creating a group
- Go to the groups page and click "Create group".
- Fill in the name.
- Add some entitlements.
- Submit the form.
- The group should appear in the table.
- Use the fga CLI to check that entitlements were created.
https://warthogs.atlassian.net/browse/WD-10185
https://warthogs.atlassian.net/browse/WD-10188

WD-10185 - feat: add create group panel

---

src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/EditGroupPanel/index.ts
src/components/pages/Groups/EditGroupPanel/types.ts
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Groups/Groups.tsx
src/components/pages/Groups/types.ts
src/components/pages/Roles/Roles.tsx
src/hooks/usePanel.test.tsx
src/hooks/usePanel.tsx
src/hooks/usePanelPortal.ts
src/test/setup.ts

- add group entitlements editing
- move panel logic to a hook
- Go to the group page
- Open the edit panel for a group
- Change some entitlements
- Save and the entitlements should get updated
- https://warthogs.atlassian.net/browse/WD-10191
- https://warthogs.atlassian.net/browse/WD-10472

WD-10191 - feat: edit group entitlements

---

openapi.yaml
package.json
src/api/api.schemas.ts
src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
src/components/pages/Groups/AddGroupPanel/types.ts
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/GroupPanel/types.ts
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
src/components/pages/Groups/IdentitiesPanelForm/index.ts
src/components/pages/Groups/IdentitiesPanelForm/types.ts
src/test/ComponentProviders.tsx

- Add a form to add users to a group
- Open the create group form.
- Click Add users
- Fill out the form
- Go back to the first panel and submit
- Use the FGA CLI to check that the user was added to the group
https://warthogs.atlassian.net/browse/WD-10186

WD-10186 - feat: add user form to group panel

---

src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
src/components/pages/Groups/AddGroupPanel/types.ts
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/GroupPanel/types.ts
src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
src/components/pages/Groups/RolesPanelForm/index.ts
src/components/pages/Groups/RolesPanelForm/types.ts
src/scss/index.scss

- Add a form to add roles to a group
- Open the create group form.
- Click Add roles
- Fill out the form
- Go back to the first panel and submit
- Use the FGA CLI to check that the role was added to the group
https://warthogs.atlassian.net/browse/WD-10187

WD-10187 - feat: add role form to group panel

---

src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
src/components/EntitlementsPanelForm/types.ts
src/components/PanelTableForm/PanelTableForm.test.tsx
src/components/PanelTableForm/PanelTableForm.tsx
src/components/PanelTableForm/_panel-table-form.scss
src/components/PanelTableForm/index.ts
src/components/PanelTableForm/types.ts
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
src/components/pages/Groups/IdentitiesPanelForm/types.ts
src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
src/components/pages/Groups/RolesPanelForm/types.ts

- Make a reusable component to handle forms with tables in panels.
- Add search to panels
- Go to the add group panel
- Click on each sub-form and check that you can add, remove and search.
- https://warthogs.atlassian.net/browse/WD-10969

WD-10969 - refactor: make reusable table/form component

---

openapi.yaml
src/api/api.schemas.ts
src/api/groups-id/groups-id.msw.ts
src/api/groups-id/groups-id.ts
src/api/groups/groups.msw.ts
src/api/groups/groups.ts
src/api/roles-id/roles-id.msw.ts
src/api/roles/roles.msw.ts
src/api/roles/roles.ts
src/components/SubFormPanel/SubFormPanel.test.tsx
src/components/SubFormPanel/SubFormPanel.tsx
src/components/SubFormPanel/types.ts
src/components/ToastCard/ToastCard.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/GroupPanel/types.ts
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
src/components/pages/Roles/RolePanel/RolePanel.test.tsx
src/components/pages/Roles/RolePanel/RolePanel.tsx
src/components/pages/Roles/RolePanel/types.ts
src/components/pages/Roles/Roles.test.tsx

support name fields when creating roles and groups
https://warthogs.atlassian.net/browse/WD-10992

WD-10992 - refactor: support name fields

---

package.json
src/components/CleanFormikField/CleanFormikField.test.tsx
src/components/NoEntityCard/NoEntityCard.test.tsx
src/components/NoEntityCard/NoEntityCard.tsx
src/components/PanelTableForm/PanelTableForm.test.tsx
src/components/SubFormPanel/SubFormPanel.tsx
src/components/pages/Groups/Groups.tsx
yarn.lock

- Add padding to loading state in `SubFormPanel`.
- Update `react-components` in order to get the fix for `EmptyState` component.
- For any user or group, press the edit button and check that the padding for the loading state is consistent with the content that gets loaded afterward.
- https://warthogs.atlassian.net/browse/WD-11566

WD-11566 - fix: add padding to loading state in SubFormPanel

---

src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Roles/Roles.tsx
src/components/pages/Roles/index.ts
src/components/pages/Roles/types.ts

- Add roles page (minus panels).
- Check that you can view the roles page.
https://warthogs.atlassian.net/browse/WD-12387

WD-12387 - feat: add roles page

---

src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
src/components/EntitlementsPanelForm/types.ts
src/components/PanelTableForm/PanelTableForm.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/EditGroupPanel/index.ts
src/components/pages/Groups/EditGroupPanel/types.ts
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/GroupPanel/types.ts
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Groups/Groups.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
src/components/pages/Groups/IdentitiesPanelForm/types.ts
src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
src/components/pages/Groups/RolesPanelForm/types.ts

- Migrate the edit group panel.
- Go to the groups page and check that you can open the edit group panel.
https://warthogs.atlassian.net/browse/WD-12385

WD-12385 - feat: edit group panel

---

src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
src/components/pages/Roles/AddRolePanel/index.ts
src/components/pages/Roles/AddRolePanel/types.ts
src/components/pages/Roles/RolePanel/RolePanel.test.tsx
src/components/pages/Roles/RolePanel/RolePanel.tsx
src/components/pages/Roles/RolePanel/index.ts
src/components/pages/Roles/RolePanel/types.ts
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Roles/Roles.tsx
src/components/pages/Roles/types.ts

- Migrate the add role panel.
- Go to the roles page and check you can open the panel to add a role.
https://warthogs.atlassian.net/browse/WD-12388

WD-12388 - feat: add role panel

---

src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
src/components/pages/Roles/EditRolePanel/index.ts
src/components/pages/Roles/EditRolePanel/types.ts
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Roles/Roles.tsx

Add the edit role panel.
- Go to the roles page and check that you can open the edit role panel.
- https://warthogs.atlassian.net/browse/WD-12389

WD-12389 - feat: edit role panel

---

src/components/DeleteEntityPanel/DeleteEntityPanel.test.tsx
src/components/DeleteEntityPanel/DeleteEntityPanel.tsx
src/components/DeleteEntityPanel/index.ts
src/components/DeleteEntityPanel/types.ts
src/components/FormPanel/FormPanel.test.tsx
src/components/FormPanel/FormPanel.tsx
src/components/FormPanel/index.ts
src/components/FormPanel/types.ts
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/types.ts
src/components/pages/Groups/DeleteGroupsPanel/DeleteGroupsPanel.test.tsx
src/components/pages/Groups/DeleteGroupsPanel/DeleteGroupsPanel.tsx
src/components/pages/Groups/DeleteGroupsPanel/index.ts
src/components/pages/Groups/DeleteGroupsPanel/types.ts
src/components/pages/Groups/EditGroupPanel/types.ts
src/components/pages/Groups/GroupPanel/index.ts
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Groups/Groups.tsx
src/components/pages/Roles/RolePanel/RolePanel.test.tsx

- Add the delete group panel.
- Go to the groups page and check that you can open the delete group panel.
https://warthogs.atlassian.net/browse/WD-12386

WD-12386 - feat: delete groups panel

---

src/components/pages/Roles/DeleteRolesPanel/DeleteRolesPanel.test.tsx
src/components/pages/Roles/DeleteRolesPanel/DeleteRolesPanel.tsx
src/components/pages/Roles/DeleteRolesPanel/index.ts
src/components/pages/Roles/DeleteRolesPanel/types.ts
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Roles/Roles.tsx

- Migrate the delete role panel.
- Go to the roles page and check that you can open the delete panel.
https://warthogs.atlassian.net/browse/WD-12390

WD-12390 - feat: delete role panel

---

src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx

- Merge the calls that update roles in a group.
https://warthogs.atlassian.net/browse/WD-12608

WD-12608 - refactor: merge calls for updating roles

---

src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx

- Merge the calls for updating a group's identities.
https://warthogs.atlassian.net/browse/WD-12607

WD-12607 - refactor: merge calls for updating identities

---

src/api/groups/groups.msw.ts
src/api/groups/groups.ts
src/api/roles/roles.msw.ts
src/api/roles/roles.ts
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx

- Rebuild the API with updated response types.
- Connect to the new ReBAC API.
- Go to the roles page.
- Open the create-role panel and check that once submitted it creates a role.
https://warthogs.atlassian.net/browse/WD-13089

WD-13089 - refactor: built latest API spec

---

.github/workflows/tics-coverage.yml

- remove tics report upload to prevent a security issue

chore(ci) remove ticls report upload to prevent a security issue

---

src/components/SubFormPanel/SubFormPanel.test.tsx
src/components/SubFormPanel/SubFormPanel.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Roles/RolePanel/RolePanel.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx

- Make all panels medium width.
- Open some panels and check they're all medium width.
https://warthogs.atlassian.net/browse/WD-13334

WD-13334 - feat: make all panels medium width

---

README.md
src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/ReBACAdmin/types.ts
src/test/utils.tsx

Use the host app's React Query QueryContext if available.
This is the same change as https://github.com/canonical/rebac-admin/pull/141 but for the Admin UI feature branch.
https://warthogs.atlassian.net/browse/WD-13635

WD-13635 - feat: support parent query context

---

README.md
src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/ReBACAdmin/types.ts
src/test/utils.tsx

Use the host app's React Query QueryContext if available.
https://warthogs.atlassian.net/browse/WD-13634

WD-13634 - feat: support parent query context

---

README.md
orval.config.ts
src/api-utils/mutator/custom-instance.ts
src/api/authentication/authentication.ts
src/api/capabilities/capabilities.ts
src/api/entitlements/entitlements.ts
src/api/groups/groups.ts
src/api/identities/identities.ts
src/api/meta/meta.ts
src/api/resources/resources.ts
src/api/roles/roles.ts
src/components/ReBACAdmin/ReBACAdmin.test.tsx
src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Users/User/User.test.tsx
src/test/setup.ts

- Set up a custom Axios instance.
- Accept an Axios instance passed in as a prop.
https://warthogs.atlassian.net/browse/WD-14005

WD-14005 - feat: accept custom Axios instance

---

README.md
demo/src/main.tsx
orval.config.ts
src/api-utils/mutator/custom-instance.ts
src/api/authentication-id/authentication-id.ts
src/api/authentication/authentication.ts
src/api/entitlements/entitlements.ts
src/api/groups-id/groups-id.ts
src/api/groups/groups.ts
src/api/resources/resources.ts
src/api/roles-id/roles-id.ts
src/api/roles/roles.ts
src/api/users-id/users-id.ts
src/api/users/users.ts
src/components/ReBACAdmin/ReBACAdmin.test.tsx
src/components/ReBACAdmin/ReBACAdmin.tsx
src/test/setup.ts

- Set up a custom Axios instance.
- Accept an Axios instance passed in as a prop.
- Removed redundant authToken support.
https://warthogs.atlassian.net/browse/WD-14006

WD-14006 - feat: accept custom Axios instance

---

src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/pages/Users/AccountManagementTab/AccountManagementTab.test.tsx
src/components/pages/Users/AccountManagementTab/AccountManagementTab.tsx
src/components/pages/Users/AccountManagementTab/index.ts
src/components/pages/Users/AccountManagementTab/types.ts
src/components/pages/Users/DeleteUsersModal/DeleteUsersModal.tsx
src/components/pages/Users/DeleteUsersModal/types.ts
src/components/pages/Users/EntitlementsTab/EntitlementsTab.test.tsx
src/components/pages/Users/Users.tsx
src/test/ComponentProviders.tsx
src/test/utils.tsx

- Add delete to user's account management page.
- Go to a user details page and click 'Account management'.
- Click the delete button, typing in the confirmation and confirm.
- The user should get deleted and you should get redirected back to the user list.
https://warthogs.atlassian.net/browse/WD-12403

WD-12403 - feat: add delete user

---

src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
src/components/pages/Users/AddUserPanel/AddUserPanel.tsx
src/components/pages/Users/AddUserPanel/types.ts
src/components/pages/Users/UserPanel/UserPanel.test.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx
src/components/pages/Users/UserPanel/types.ts

- Add entitlements form to create users panel.
- https://warthogs.atlassian.net/browse/WD-12394

WD-12394 - feat: add entitlements form to create users panel

---

src/components/EntityTable/EntityTable.test.tsx
src/components/EntityTable/EntityTable.tsx
src/components/EntityTable/index.ts
src/components/EntityTable/types.ts
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Groups/Groups.tsx
src/components/pages/Groups/types.ts
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Roles/Roles.tsx
src/components/pages/Roles/types.ts
src/components/pages/Users/Users.tsx
src/hooks/useEntitiesSelect.ts

- Make reusable table component in preparation for adding pagination.
https://warthogs.atlassian.net/browse/WD-14337

WD-14337 - refactor: create reusable entity table

---

src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
src/components/pages/Users/AddUserPanel/AddUserPanel.tsx
src/components/pages/Users/AddUserPanel/types.ts
src/components/pages/Users/UserPanel/UserPanel.test.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx
src/components/pages/Users/UserPanel/types.ts

- Add roles form to create users panel.
- https://warthogs.atlassian.net/browse/WD-12393

WD-12393 - feat: add roles form to create users panel

---

src/components/GroupsPanelForm/GroupsPanelForm.test.tsx
src/components/GroupsPanelForm/GroupsPanelForm.tsx
src/components/GroupsPanelForm/index.ts
src/components/GroupsPanelForm/types.ts
src/components/RolesPanelForm/RolesPanelForm.test.tsx
src/components/pages/Groups/Groups.test.tsx
src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
src/components/pages/Users/AddUserPanel/AddUserPanel.tsx
src/components/pages/Users/AddUserPanel/types.ts
src/components/pages/Users/UserPanel/UserPanel.test.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx
src/components/pages/Users/UserPanel/types.ts
src/mocks/groups.ts
src/scss/index.scss

- Add groups form to create users panel.
- https://warthogs.atlassian.net/browse/WD-12395

WD-12395 - feat: add groups form to create users panel

---

src/components/pages/Groups/Groups.test.tsx
src/components/pages/Groups/Groups.tsx
src/components/pages/Groups/types.ts
src/components/pages/Roles/Roles.test.tsx
src/components/pages/Roles/Roles.tsx
src/components/pages/Roles/types.ts
src/components/pages/Users/Users.test.tsx
src/components/pages/Users/Users.tsx
src/components/pages/Users/types.ts
src/test/queries/tables.ts
src/test/queries/within.ts
src/test/utils.tsx

- Update table columns to match the designs.
- Add custom matcher to make querying tables less fragile.
- Go to the users page.
- Check that the columns match the designs (without the counts).
- Go to roles and groups tables and check that the name header has been updated.
https://warthogs.atlassian.net/browse/WD-13092
https://warthogs.atlassian.net/browse/WD-13091
https://warthogs.atlassian.net/browse/WD-13090

WD-13090 - feat: update table columns

---

src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
src/components/GroupsPanelForm/GroupsPanelForm.test.tsx
src/components/MultiSelectField/MultiSelectField.test.tsx
src/components/PanelForm/PanelForm.test.tsx
src/components/PanelTableForm/PanelTableForm.test.tsx
src/components/RolesPanelForm/RolesPanelForm.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/DeleteGroupsModal/DeleteGroupsModal.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
src/components/pages/Roles/DeleteRolesModal/DeleteRolesModal.test.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
src/components/pages/Users/DeleteUsersModal/DeleteUsersModal.test.tsx
src/components/pages/Users/EntitlementsTab/EntitlementsTab.test.tsx
src/components/pages/Users/GroupsTab/GroupsTab.test.tsx
src/components/pages/Users/RolesTab/RolesTab.test.tsx
src/test/queries/index.ts
src/test/queries/notifications.ts
src/test/queries/queries.ts
src/test/queries/spinners.ts
src/test/queries/within.ts
src/test/utils.tsx

- Add custom queries for getting spinners and notifications in tests.
- Update tests to use those queries.
https://warthogs.atlassian.net/browse/WD-14600

WD-14600 - test: add custom queries for testing for notifications and spinners

---

src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/Groups.tsx
src/components/pages/Roles/Roles.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
src/components/pages/Users/EditUserPanel/index.ts
src/components/pages/Users/EditUserPanel/types.ts
src/components/pages/Users/UserPanel/UserPanel.test.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx
src/components/pages/Users/UserPanel/types.ts
src/components/pages/Users/Users.test.tsx
src/components/pages/Users/Users.tsx

- Add user's entitlements form to edit panel
- https://warthogs.atlassian.net/browse/WD-12398

WD-12398 - feat: add user's entitlements form to edit panel

---

src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
src/components/EntityTable/EntityTable.tsx
src/components/GroupsPanelForm/GroupsPanelForm.test.tsx
src/components/GroupsPanelForm/GroupsPanelForm.tsx
src/components/PanelTableForm/PanelTableForm.test.tsx
src/components/PanelTableForm/PanelTableForm.tsx
src/components/PanelTableForm/types.ts
src/components/RolesPanelForm/RolesPanelForm.test.tsx
src/components/RolesPanelForm/RolesPanelForm.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx

- Replace the identical filtering and matching functions with generic methods inside `PanelTableForm`.
https://warthogs.atlassian.net/browse/WD-14648

WD-14648 - refactor: dedupe the matching and filtering functions

---

src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
src/components/pages/Users/EditUserPanel/types.ts
src/components/pages/Users/UserPanel/UserPanel.test.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx
src/components/pages/Users/UserPanel/types.ts

- Add edit user's roles form to edit panel.
-https://warthogs.atlassian.net/browse/WD-12397

WD-12397 - feat: add edit user's roles form to edit panel

---

src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/pages/Entitlements/Entitlements.test.tsx
src/components/pages/Entitlements/Entitlements.tsx
src/components/pages/Entitlements/index.ts
src/components/pages/Entitlements/types.ts

- Add entitlements page
- Click on Entitlements in the side menu.
- You should see a table of entitlements.
https://warthogs.atlassian.net/browse/WD-14680

WD-14680 - feat: add entitlements page

---

src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/pages/Entitlements/Entitlements.test.tsx
src/components/pages/Resources/Resources.test.tsx
src/components/pages/Resources/Resources.tsx
src/components/pages/Resources/index.ts
src/components/pages/Resources/types.ts

Added the resources page.
- Click on Resources in the sidebar and you should see a table of resources.
https://warthogs.atlassian.net/browse/WD-14684

WD-14684 - feat: add resources page

---

src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.tsx

- invalidate queries for updated entities.
- Go to the edit panels and make some changes in the sub forms.
- Save the form and then reopen it.
- The updated entities should appear.
https://warthogs.atlassian.net/browse/WD-14784

WD-14784 - fix: reload updated queries

---

src/components/ReBACAdmin/ReBACAdmin.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
src/components/pages/Roles/EditRolePanel/types.ts
src/components/pages/Roles/RolePanel/Fields/Fields.test.tsx
src/components/pages/Roles/RolePanel/Fields/Fields.tsx
src/components/pages/Roles/RolePanel/Fields/index.ts
src/components/pages/Roles/RolePanel/Fields/types.ts
src/components/pages/Roles/RolePanel/RolePanel.test.tsx
src/components/pages/Roles/RolePanel/RolePanel.tsx
src/components/pages/Roles/RolePanel/types.ts
src/components/pages/Roles/Roles.tsx

- Enable editing role names.
- Go to the role table.
- Open the edit form for a role.
- Change the role name and submit the form.
- The table should update with the new name.
https://warthogs.atlassian.net/browse/WD-14895

feat: edit role name

---

src/components/pages/Users/AddUserPanel/AddUserPanel.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
src/components/pages/Users/EditUserPanel/types.ts
src/components/pages/Users/User/User.tsx
src/components/pages/Users/UserPanel/Fields/Fields.test.tsx
src/components/pages/Users/UserPanel/Fields/Fields.tsx
src/components/pages/Users/UserPanel/Fields/index.ts
src/components/pages/Users/UserPanel/Fields/types.ts
src/components/pages/Users/UserPanel/UserPanel.test.tsx
src/components/pages/Users/UserPanel/UserPanel.tsx
src/components/pages/Users/UserPanel/index.ts
src/components/pages/Users/UserPanel/types.ts
src/components/pages/Users/Users.tsx

- Update user details in edit form.
- TODO: Fix and add tests.
- https://warthogs.atlassian.net/browse/WD-14894

WD-14894 - feat: update user details in edit form

---

src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
src/components/pages/Groups/EditGroupPanel/types.ts
src/components/pages/Groups/GroupPanel/Fields/Fields.test.tsx
src/components/pages/Groups/GroupPanel/Fields/Fields.tsx
src/components/pages/Groups/GroupPanel/Fields/index.ts
src/components/pages/Groups/GroupPanel/Fields/types.ts
src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
src/components/pages/Groups/GroupPanel/GroupPanel.tsx
src/components/pages/Groups/GroupPanel/index.ts
src/components/pages/Groups/GroupPanel/types.ts
src/components/pages/Groups/Groups.tsx

- Update group name in edit form.
- https://warthogs.atlassian.net/browse/WD-14896

WD-14896 - feat: update group name in edit form

---

HACKING.md
README.md
package.json
yarn.lock

- Update the package name for the feature branch to be used specifically with admin-ui.
https://warthogs.atlassian.net/browse/WD-16022

WD-16022 - build: update package name for admin-ui

---

.github/workflows/tics-coverage.yml
.github/workflows/tiobe_archive.txt

Filter the files analysed by TICS.

chore(ci): filter files analysed by tics

---

package.json
src/components/MultiSelectField/MultiSelectField.tsx
src/components/PanelTableForm/PanelTableForm.tsx
src/hooks/usePagination.ts
yarn.lock

Replace deprecated lodash.isEqual with fast-deep-equal.

chore(deps): replace deprecated lodash.isEqual

---

package.json
vite.config.ts

Remove unused polyfill import.

refactor: remove polyfill import

---

.github/workflows/tics-coverage.yml

- Update the TICS workflow to use the tics action, run weekly, run on self hosted and support manually running.

chore(CI): update tics workflow

---

eslint.config.mjs
src/components/EntitlementsPanelForm/Fields/Fields.tsx
src/components/EntityTable/EntityTable.tsx
src/components/GroupsPanelForm/GroupsPanelForm.tsx
src/components/MultiSelectField/MultiSelectField.tsx
src/components/RolesPanelForm/RolesPanelForm.tsx
src/components/pages/Entitlements/Entitlements.tsx
src/components/pages/Resources/Resources.tsx
src/test/mocks/capabilities.ts
src/test/utils.tsx

- Add prefer-nullish-coalescing and fix issues.
- It also adds prefer-optional-chain but there were no fixes to make.

chore(lint): add prefer-nullish-coalescing rule
