- .github/workflows/actions.yml
- .github/workflows/test.yml
- Make CI work for `admin-service-api` branch.
- https://warthogs.atlassian.net/browse/WD-10055
> WD-10055 - fix: make CI work for admin-service-api

- .gitignore
- openapi.yaml
- src/api/api.schemas.ts
- src/api/authentication-id/authentication-id.msw.ts
- src/api/authentication/authentication.msw.ts
- src/api/entitlements/entitlements.msw.ts
- src/api/groups-id/groups-id.msw.ts
- src/api/groups/groups.msw.ts
- src/api/resources/resources.msw.ts
- src/api/roles-id/roles-id.msw.ts
- src/api/roles/roles.msw.ts
- src/api/users-id/users-id.msw.ts
- src/api/users/users.msw.ts
- src/components/ReBACAdmin/ReBACAdmin.tsx
- src/components/pages/Groups/Groups.test.tsx
- src/components/pages/Groups/Groups.tsx
- src/components/pages/Groups/index.ts
- src/components/pages/Groups/types.ts
- src/components/pages/Roles/Roles.test.tsx
- src/components/pages/Roles/Roles.tsx
- src/components/pages/Roles/index.ts
- src/components/pages/Roles/types.ts
- src/components/pages/Users/Users.tsx
- src/mocks/groups.ts
- src/mocks/roles.ts
- Set up views for groups and roles.
- Modify the responses for groups and roles in `openapi.yaml` to be consistent with [identity-platform-admin-ui](https://github.com/canonical/identity-platform-admin-ui).
- Remove `openapi.yaml` from `.gitignore`.
- Regenerate api files with `Orval`.
- https://warthogs.atlassian.net/browse/WD-10024
> WD-10024 - feat: set up views for groups and roles

- src/hooks/usePanelPortal.test.tsx
- src/hooks/usePanelPortal.ts
- Prevent form panels from closing when clicking outside/pressing escape.
- https://warthogs.atlassian.net/browse/WD-10346
> WD-10346 - fix: prevent form panels from closing when clicking outside/pressing escape

- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
- src/components/pages/Groups/EditGroupPanel/types.ts
- src/components/pages/Groups/GroupPanel/GroupPanel.tsx
- Add support for editing the users in a group.
- Go to the groups page and open the edit panel.
- Click on 'Edit users' and add some users.
- Go back to the first screen and submit the form.
- Open the edit panel again and you should see the new users.
- Now try removing some users from the group. When you save you'll get an error due to this issue: https://github.com/canonical/rebac-admin/pull/94#issuecomment-2081788918
https://warthogs.atlassian.net/browse/WD-10189
> WD-10189 - feat: edit a group's users

- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
- src/components/pages/Groups/Groups.test.tsx
- Add the ability to edit roles in a group.
- Go to the groups page and edit a group.
- Click "Edit roles".
- Add and remove some roles (note: the roles you remove need to exist, so if they don't then go to the roles page and add them).
- Submit the form to save the group.
- Reopen the edit panel and you should see the changed roles.
https://warthogs.atlassian.net/browse/WD-10190
> WD-10190 - feat: edit roles for a group

- src/components/SubFormPanel/PanelFormNavigation/PanelFormNavigation.test.tsx
- src/components/SubFormPanel/PanelFormNavigation/PanelFormNavigation.tsx
- src/components/SubFormPanel/PanelFormNavigation/types.ts
- src/components/SubFormPanel/SubFormPanel.test.tsx
- src/components/SubFormPanel/SubFormPanel.tsx
- src/components/SubFormPanel/types.ts
- src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
- src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
- src/components/pages/Groups/AddGroupPanel/types.ts
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
- src/components/pages/Groups/EditGroupPanel/types.ts
- src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
- src/components/pages/Groups/GroupPanel/GroupPanel.tsx
- src/components/pages/Groups/GroupPanel/types.ts
- src/components/pages/Groups/Groups.tsx
- src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
- src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
- src/components/pages/Roles/AddRolePanel/types.ts
- src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
- src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
- src/components/pages/Roles/EditRolePanel/types.ts
- src/components/pages/Roles/RolePanel/RolePanel.test.tsx
- src/components/pages/Roles/RolePanel/RolePanel.tsx
- src/components/pages/Roles/RolePanel/types.ts
- src/components/pages/Roles/Roles.tsx
- src/hooks/usePanel.test.tsx
- src/hooks/usePanel.tsx
- src/hooks/usePanelPortal.ts
- Support the ability to change the panel width.
- Set a medium width only for the entitlements panel.
- Open the add roles or groups panel.
- Click on 'Add entitlements' and notice that the panel gets wider.
- Navigate back to the first screen and the panel should get narrower again.
https://warthogs.atlassian.net/browse/WD-10954
> WD-10954 - feat: support changing panel widths

- src/components/ReBACAdmin/ReBACAdmin.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- mock the websocket to prevent errors when rendering the ReBACAdm in component in the tests
https://warthogs.atlassian.net/browse/WD-10968
> WD-10968 - fix: fix test websocket errors

- src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
- src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
- src/components/EntitlementsPanelForm/types.ts
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
- src/components/pages/Groups/IdentitiesPanelForm/types.ts
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
- src/components/pages/Groups/RolesPanelForm/types.ts
- Display empty states inside the panel forms.
- Open the "Add group" panel.
- Click on each of the subforms and you should see the empty state for that form (currently with the icon on top until it gets updated in React Components).
https://warthogs.atlassian.net/browse/WD-10967
> WD-10967 - feat: add empty states to panels

- src/components/CleanFormikField/CleanFormikField.test.tsx
- src/components/CleanFormikField/CleanFormikField.tsx
- src/components/CleanFormikField/index.ts
- src/components/CleanFormikField/types.ts
- src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
- src/components/PanelForm/PanelForm.test.tsx
- src/components/pages/Groups/GroupPanel/GroupPanel.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
- src/components/pages/Roles/RolePanel/RolePanel.tsx
- Display errors only when the form is dirty. This is to prevent the buttons jumping when you click outside a field and haven't entered anything.
- Go to the group panel
- click on entitlements and notice that the screen doesn't jump
- click inside a field and then outside and the validation shouldn't appear.
- Enter something in a field and notice that the validation will appear if you click in then outside of another field.
https://warthogs.atlassian.net/browse/WD-10993
> WD-10993 - feat: only display errors on dirty forms

- .github/workflows/actions.yml
- package.json
- src/components/pages/Groups/Groups.test.tsx
- src/components/pages/Groups/Groups.tsx
- src/components/pages/Groups/types.ts
- src/components/pages/Roles/Roles.test.tsx
- src/components/pages/Roles/Roles.tsx
- src/components/pages/Roles/types.ts
- Fix panels that were not displayed if there was no data.
- View the roles and groups pages with no roles/groups data and check that you can open the "add" panels.
https://warthogs.atlassian.net/browse/WD-12970
> WD-12970 - fix: display panels when there is no data

- src/components/pages/Groups/Groups.test.tsx
- src/components/pages/Groups/Groups.tsx
- src/components/pages/Roles/Roles.test.tsx
- src/components/pages/Roles/Roles.tsx
- Fix roles and groups panels where there is no data.
- Go to the roles and groups pages when you have no roles or groups and check that you can open the "add" panel.
https://warthogs.atlassian.net/browse/WD-12971
> WD-12971 - fix: display panels when there is no data

- src/components/SubFormPanel/index.ts
- src/components/pages/Users/DeleteUsersPanel/DeleteUsersPanel.test.tsx
- src/components/pages/Users/DeleteUsersPanel/DeleteUsersPanel.tsx
- src/components/pages/Users/DeleteUsersPanel/index.ts
- src/components/pages/Users/DeleteUsersPanel/types.ts
- src/components/pages/Users/UserPanel/index.ts
- src/components/pages/Users/UserPanel/types.ts
- src/components/pages/Users/Users.test.tsx
- src/components/pages/Users/Users.tsx
- src/components/pages/Users/types.ts
- Add support for deleting users.
- Go to the users panel and check that you can open the delete panel.
Note: the checkboxes don't currently work with the mock API as the ID is not generated from the mocks. I've asked about how to handle deleting a user if the id is not defined (this is an issue that's not specific to identities).
https://warthogs.atlassian.net/browse/WD-12391
> WD-12391 - feat: delete users panel

- src/components/ListCard/ListCard.test.tsx
- src/components/ListCard/ListCard.tsx
- src/components/ListCard/ListCardList/ListCardList.test.tsx
- src/components/ListCard/ListCardList/ListCardList.tsx
- src/components/ListCard/ListCardList/_list-card-list.scss
- src/components/ListCard/ListCardList/index.ts
- src/components/ListCard/ListCardList/types.ts
- src/components/ListCard/_list-card.scss
- src/components/ListCard/index.ts
- src/components/ListCard/types.ts
- src/components/ReBACAdmin/ReBACAdmin.tsx
- src/components/pages/Users/SummaryTab/SummaryTab.test.tsx
- src/components/pages/Users/SummaryTab/SummaryTab.tsx
- src/components/pages/Users/SummaryTab/index.ts
- src/components/pages/Users/SummaryTab/types.ts
- Add user summary tab (without counts as that's not currently possible).
- Go to the user list and click on a user and you should see the user's summary tab with some details.
https://warthogs.atlassian.net/browse/WD-12399
> feat: add user summary

- src/components/CleanFormikField/CleanFormikField.tsx
- src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
- src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
- src/components/pages/Groups/AddGroupPanel/types.ts
- src/components/pages/Groups/DeleteGroupsPanel/types.ts
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
- src/components/pages/Groups/EditGroupPanel/types.ts
- src/components/pages/Groups/Groups.test.tsx
- src/components/pages/Groups/Groups.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
- src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
- src/components/pages/Roles/DeleteRolesPanel/types.ts
- src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
- src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
- src/components/pages/Roles/EditRolePanel/types.ts
- src/components/pages/Roles/Roles.test.tsx
- src/components/pages/Roles/Roles.tsx
- src/components/pages/Users/Users.tsx
- src/utils/getIds.test.ts
- src/utils/getIds.ts
- Use entity ids for all operations.
- Temporarily implement selecting identites and roles from the API.
- Go to a form such as for adding a group.
- Fill in the form and add some related entities and submit.
- The group should get added and opening the edit form should show the related entities.
https://warthogs.atlassian.net/browse/WD-13045
> WD-13045 - refactor: use ids for operating on entities

- src/components/Content/Content.test.tsx
- src/components/Content/Content.tsx
- src/components/Content/_content.scss
- src/components/pages/Groups/Groups.test.tsx
- src/components/pages/Groups/Groups.tsx
- src/components/pages/Roles/Roles.test.tsx
- src/components/pages/Roles/Roles.tsx
- src/components/pages/Users/Users.test.tsx
- src/components/pages/Users/Users.tsx
Add search to the users, roles and groups pages.
- Open the network dev tools.
- Go to the users, groups and roles pages.
- Enter something in the search field and submit.
- Check that the network request was made with ?filter=[your search string] (the example app does not have filtering implemented so this won't actually return filtered results).
https://warthogs.atlassian.net/browse/WD-13336
https://warthogs.atlassian.net/browse/WD-13337
https://warthogs.atlassian.net/browse/WD-13338
> WD-13336 - feat: add search to users, roles and groups

- .github/workflows/tics-coverage.yml
[List of work items including drive-bys]
- Pull code
- Run `dotrun clean && dotrun serve`
- Open http://0.0.0.0:8036/
- [Add additional steps]
[List of links to issues/bugs and cards if needed]
[if relevant, include a screenshot]
> ci: update TICSAUTHTOKEN in workflow

- src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
- src/components/EntitlementsPanelForm/Fields/Fields.tsx
- src/components/EntitlementsPanelForm/types.ts
- src/components/FormikSubmitButton/index.ts
- src/components/ReBACAdmin/ReBACAdmin.tsx
- src/components/pages/Users/EntitlementsTab/EntitlementsTab.test.tsx
- src/components/pages/Users/EntitlementsTab/EntitlementsTab.tsx
- src/components/pages/Users/EntitlementsTab/index.ts
- src/components/pages/Users/EntitlementsTab/types.ts
- src/components/pages/Users/SummaryTab/SummaryTab.tsx
- src/components/pages/Users/SummaryTab/index.ts
- src/components/pages/Users/SummaryTab/types.ts
- src/mocks/entitlements.ts
- src/mocks/resources.ts
- src/test/utils.tsx
- Add user entitlements tab.
- Add util for finding spinners.
Note: this will require the following fix to be able to delete entitlements: https://github.com/canonical/rebac-admin-ui-handlers/pull/23.
- Go to the users table and click on a user.
- Click on the 'Entitlements' tab.
- Use the form to add an entitlement and it should appear in the table.
- Click the delete icon and it should delete an entitlement.
https://warthogs.atlassian.net/browse/WD-12402
> WD-12402 - feat: add user entitlements tab

- package.json
- src/components/MultiSelectField/MultiSelectField.test.tsx
- src/components/MultiSelectField/MultiSelectField.tsx
- src/components/MultiSelectField/_multi-select-field.scss
- src/components/MultiSelectField/index.ts
- src/components/MultiSelectField/types.ts
- src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
- src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
- src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
- src/components/pages/Groups/RolesPanelForm/types.ts
- src/mocks/roles.ts
- src/scss/_vanilla-overrides.scss
- src/scss/index.scss
- yarn.lock
- Add component to handle multi-selection of entities.
- Update roles form to use the multi-select.
- Go to groups page.
- Open the panel to add or edit a group.
- Open the roles form.
- Open the select and you should be able to select multiple roles.
- You can also perform searches, but filtering is not implemented in the rebac example API.
https://warthogs.atlassian.net/browse/WD-14233
https://warthogs.atlassian.net/browse/WD-12646
> feat: add multi-select component and add to roles form

- src/components/RolesPanelForm/RolesPanelForm.test.tsx
- src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
- src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
- src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
- src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
- src/components/pages/Groups/IdentitiesPanelForm/types.ts
- src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
- src/components/pages/Users/UserPanel/UserPanel.test.tsx
- src/components/pages/Users/UserPanel/UserPanel.tsx
- Add a multi-select for users subform.
- Go to groups page.
- Open the panel to add or edit a group.
- Open the users form.
- Open the select and you should be able to select multiple users.
- You can also perform searches, but filtering is not implemented in the rebac example API.
https://warthogs.atlassian.net/browse/WD-12647
> WD-12647 - feat: add multi-select for users form

- src/components/ReBACAdmin/ReBACAdmin.tsx
- src/components/pages/Users/GroupsTab/GroupsTab.test.tsx
- src/components/pages/Users/GroupsTab/GroupsTab.tsx
- src/components/pages/Users/GroupsTab/index.ts
- src/components/pages/Users/GroupsTab/types.ts
- Add groups tab to user's details.
- Click on a user in the users table and click on the groups tab.
- Check that you can add/remove groups.
https://warthogs.atlassian.net/browse/WD-12401
https://warthogs.atlassian.net/browse/WD-12410
> WD-12401 - feat: add user details groups tab

- src/components/pages/Users/User/User.test.tsx
- src/components/pages/Users/User/User.tsx
- src/components/pages/Users/User/types.ts
- src/components/pages/Users/UserPanel/UserPanel.test.tsx
- src/components/pages/Users/UserPanel/UserPanel.tsx
- Add user details edit form.
- Navigate to users page and click on any of the user to open the user details page.
- Check that the edit button appears on the top right corner and that it opens the edit users panel.
- https://warthogs.atlassian.net/browse/WD-12405
> WD-12405 - feat: add user details edit form

- HACKING.md
- README.md
- package.json
- src/components/ReBACAdmin/ReBACAdmin.test-d.ts
- src/components/ReBACAdmin/ReBACAdmin.tsx
- vite.config.ts
- yarn.lock
- Make React Router a peer dep so that the host's router is used as this is now required with React Router v7.
> refactor: make react-router peer dep
